import {
  ProductChairRequest,
  ProductDeskRequest,
  ProductHeadphoneRequest,
  ProductKeyboardRequest,
  ProductMonitorRequest,
  ProductMouseRequest,
} from '../libs/api-interfaces/src';

const KEYBOARDS: Omit<ProductKeyboardRequest, 'kind'>[] = [
  {
    name: 'K2 (Hot-Swappable) Version 2',
    price: 7840,
    description: '',
    images: [
      'https://keychron.in/wp-content/uploads/2021/04/Keychron-K2-hot-swappable-wireless-mechanical-keyboard-for-Mac-Windows-iOS-Gateron-switch-brown-with-type-C-RGB-white-backlight_1800x1800-300x300.jpg',
    ],
    category: 'Keyboard',
    brand: 'Keychron',
    colors: ['black', 'white'],
    type: 'Wireless',
    numberOfKeys: 84,
    illumination: 'RGB',
    keyCaps: 'PBT',
  },
  {
    name: 'Keychron K8 Wireless Mechanical Keyboard',
    price: 8999,
    description: '',
    images: [
      'https://keychron.in/wp-content/uploads/2021/04/Keychron-K2-hot-swappable-wireless-mechanical-keyboard-for-Mac-Windows-iOS-Gateron-switch-brown-with-type-C-RGB-white-backlight_1800x1800-300x300.jpg',
    ],
    category: 'Keyboard',
    brand: 'Keychron',
    colors: ['black', 'white'],
    type: 'Wireless',
    numberOfKeys: 84,
    illumination: 'LED',
    keyCaps: 'ABS',
  },
  {
    type: 'Wired',
    numberOfKeys: 84,
    illumination: 'RGB',
    keyCaps: 'PBT',
    name: 'Razer Huntsman Elite TE Wired Mechanical Keyboard',
    price: 8999,
    originalPrice: 9599,
    description:
      'Razer Hunstman Elite TE Edition is a wired mechanical keyboard. It comes with Razer Red switches for fast actuation. Per-key RGB lights can increase your gaming performance.',
    images: ['https://m.media-amazon.com/images/I/61BXjB6ufhL._SL1326_.jpg'],
    category: 'Keyboard',
    colors: ['black'],
    brand: 'Razer',
  },
  {
    type: 'Wired',
    numberOfKeys: 84,
    illumination: 'RGB',
    keyCaps: 'PBT',
    name: 'Razer Huntsman Wired Mechanical Keyboard',
    price: 12400,
    description:
      'Razer Huntsman is a full size wired keyboard. It comes with Razer brown switches and per-key RGB lighting.  Has a full number pad for your other needs.',
    images: [
      'https://www.techbooze.in/wp-content/uploads/2021/05/Razer-Huntsman-V2-Analog-Temp.jpg',
    ],
    category: 'Keyboard',
    colors: ['black'],
    brand: 'Razer',
    originalPrice: 14999,
  },
  {
    name: 'Keychron K6',
    price: 7399,
    description: '',
    images: [''],
    category: 'Keyboard',
    brand: 'Keychron',
    colors: ['black', 'white'],
    type: 'Wireless',
    numberOfKeys: 84,
    illumination: 'RGB',
    keyCaps: 'PBT',
  },
  {
    name: 'Razer BlackWidow V3 Tenkeyless',
    price: 9599,
    description: '',
    images: [''],
    category: 'Keyboard',
    brand: 'Razer',
    colors: ['black'],
    type: 'Wired',
    numberOfKeys: 84,
    illumination: 'RGB',
    keyCaps: 'PBT',
  },
  {
    name: 'Razer Ornata V2 Gaming Keyboard',
    price: 18299,
    description: '',
    images: [''],
    category: 'Keyboard',
    brand: 'Razer',
    colors: ['black'],
    type: 'Wired',
    numberOfKeys: 84,
    illumination: 'RGB',
    keyCaps: 'PBT',
  },
];

const MOUSE: Omit<ProductMouseRequest, 'kind'>[] = [
  {
    type: 'Wireless',
    buttons: 8,
    name: 'Logitech Mx Master 3 Wireless Mouse',
    price: 7500,
    originalPrice: 8299,
    description:
      'Order Logitech MX Master 3 Bluetooth and USB Unifying Laser Mouse online, to get an awesome companion. The wheel’s machined steel gives it a premium tactility and enough weight to offer dynamic inertia you feel – but don’t hear.',
    images: ['https://m.media-amazon.com/images/I/613a-3jtieL._SL1500_.jpg'],
    category: 'Mouse',
    brand: 'Logitech',
    colors: ['red'],
  },
  {
    type: 'Wireless',
    buttons: 5,
    name: 'Razer DeathAdder Essential Gaming Mouse',
    price: 1487,
    originalPrice: 4499,
    description:
      'Kickstart a proper gaming rig with the Razer DeathAdder Essential. The 6,400 DPI optical sensor enables fast and precise swipes for great control, while an ergonomic form allows for extended hours of gaming.',
    images: ['https://m.media-amazon.com/images/I/51KmYlNX6lL._SL1000_.jpg'],
    category: 'Mouse',
    brand: 'Razer',
    colors: ['black'],
  },
  {
    type: 'Wireless',
    buttons: 6,
    name: 'Razer Basilisk X Hyperspeed Wireless Gaming Mouse',
    price: 4277,
    originalPrice: 5499,
    description:
      '25% Faster Than Competing Wireless Mice: The all-new, Razer HyperSpeed wireless technology brings together extreme low-latency and interference reduction for true wireless freedom.',
    images: [''],
    category: 'Mouse',
    brand: 'Razer',
    colors: ['black'],
  },
  {
    type: 'Wireless',
    buttons: 15,
    name: 'Logitech G604 Lightspeed Wireless Gaming Mouse',
    price: 5995,
    originalPrice: 8495,
    description: '',
    images: ['https://m.media-amazon.com/images/I/613a-3jtieL._SL1500_.jpg'],
    category: 'Mouse',
    brand: 'Logitech',
    colors: ['black'],
  },
  {
    type: 'Wireless',
    buttons: 8,
    name: 'Logitech MX Master 2S Wireless Mouse',
    price: 5495,
    originalPrice: 8995,
    description:
      'MX Master has been designed, developed, and engineered with its companion keyboard, MX Keys. Get a premium look and feel, seamless workflow, and advanced functionality when you team MX Master with MX Keys. ',
    images: ['https://m.media-amazon.com/images/I/613a-3jtieL._SL1500_.jpg'],
    category: 'Mouse',
    brand: 'Logitech',
    colors: ['black'],
  },
];

const CHAIR: Omit<ProductChairRequest, 'kind'>[] = [
  {
    name: 'Ikea UTESPELARE Gaming chair',
    price: 4899,
    originalPrice: 6999,
    description: '',
    images: [],
    category: 'Chair',
    brand: 'Ikea',
    colors: ['black'],
    headSupport: true,
    upholstery: 'Polyurethane foam',
  },
  {
    name: 'Secretlab TITAN Evo 2022',
    price: 48899,
    originalPrice: 65999,
    description: '',
    images: [],
    category: 'Chair',
    brand: 'Secretlab',
    colors: ['black'],
    headSupport: true,
    upholstery: 'Acrylic',
  },
  {
    name: 'Ikea MARKUS office chair',
    price: 14990,
    originalPrice: 16499,
    description: '',
    images: [],
    category: 'Chair',
    brand: 'Ikea',
    colors: ['black'],
    headSupport: true,
    upholstery: 'Polyurethane foam',
  },
  {
    name: 'Ikea RENBERGET office chair',
    price: 5290,
    originalPrice: 6499,
    description: '',
    images: [],
    category: 'Chair',
    brand: 'Ikea',
    colors: ['black'],
    headSupport: false,
    upholstery: 'Polyurethane foam',
  },
  {
    name: 'Ikea GRUPPSPEL Gaming chair',
    price: 19990,
    originalPrice: 22499,
    description: '',
    images: [],
    category: 'Chair',
    brand: 'Ikea',
    colors: ['grey'],
    headSupport: true,
    upholstery: 'Polyurethane foam',
  },
  {
    name: 'Green Soul Ergonomics Gaming chair',
    price: 18990,
    originalPrice: 35533,
    description: '',
    images: [],
    category: 'Chair',
    brand: 'Green Soul',
    colors: ['black'],
    headSupport: true,
    upholstery: 'Moulded Foam',
  },
  {
    name: 'Ikea CRYSTAL V2 Office chair',
    price: 8290,
    originalPrice: 10299,
    description: '',
    images: [],
    category: 'Chair',
    brand: 'Green Soul',
    colors: ['black'],
    headSupport: true,
    upholstery: 'Polyurethane foam',
  },
  {
    name: 'Green Soul Ergonomics beast gaming chair',
    price: 15190,
    originalPrice: 22709,
    description: '',
    images: [],
    category: 'Chair',
    brand: 'Green Soul',
    colors: ['red'],
    headSupport: true,
    upholstery: 'Polyurethane foam',
  },
  {
    name: 'Grean Soul Thunder Multi-Functional Chair with LED RGB Lights',
    price: 19990,
    originalPrice: 39990,
    description: '',
    images: [],
    category: 'Chair',
    brand: 'Green Soul',
    colors: ['black'],
    headSupport: true,
    upholstery: 'Polyurethane foam',
  },
  {
    name: 'Green Soul NEW YORK Office Chair',
    price: 34990,
    originalPrice: 45436,
    description: '',
    images: [],
    category: 'Chair',
    brand: 'Green Soul',
    colors: ['black'],
    headSupport: true,
    upholstery: 'Polyurethane foam',
  },
];

const DESK: Omit<ProductDeskRequest, 'kind'>[] = [
  {
    name: 'Ikea LAGKAPTEN White Desk',
    price: 9999,
    originalPrice: 12999,
    description: '',
    images: ['https://wfh-store.s3.amazonaws.com/desk/lagkapten-alex-desk.webp'],
    category: 'Desk',
    brand: 'Ikea',
    colors: ['black'],
    material: 'Wood',
    heightAdjustable: false,
  },
  {
    name: 'Secretlab MAGNUS Metal Desk',
    price: 39999,
    originalPrice: 42999,
    description: '',
    images: [],
    category: 'Desk',
    brand: 'Secretlab',
    colors: ['black'],
    material: 'Metal',
    heightAdjustable: true,
  },
  {
    name: 'Ikea ALEX White Desk',
    price: 13990,
    originalPrice: 15499,
    description: '',
    images: ['https://wfh-store.s3.amazonaws.com/desk/micke-desk-white.webp'],
    category: 'Desk',
    brand: 'Ikea',
    colors: ['white'],
    material: 'Wood',
    heightAdjustable: false,
  },
  {
    name: 'Ikea MICKE White Desk',
    price: 6990,
    originalPrice: 8999,
    description: '',
    images: [],
    category: 'Desk',
    brand: 'Ikea',
    colors: ['white'],
    material: 'Wood',
    heightAdjustable: false,
  },
  {
    name: 'Ikea BEKANT Corner Desk Left',
    price: 21990,
    originalPrice: 24499,
    description: '',
    images: [
      'https://wfh-store.s3.amazonaws.com/desk/bekant-corner-desk-left-black-stained-ash-veneer-black.webp',
    ],
    category: 'Desk',
    brand: 'Ikea',
    colors: ['black'],
    material: 'Wood',
    heightAdjustable: true,
  },
  {
    name: 'Ikea BEKANT Corner Desk Right',
    price: 21990,
    originalPrice: 24499,
    description: '',
    images: [
      'https://wfh-store.s3.amazonaws.com/desk/bekant-corner-desk-right-black-stained-ash-veneer-black.webp',
    ],
    category: 'Desk',
    brand: 'Ikea',
    colors: ['black'],
    material: 'Wood',
    heightAdjustable: true,
  },
  {
    name: 'Ikea MALM desk',
    price: 10990,
    originalPrice: 12455,
    description: '',
    images: ['https://wfh-store.s3.amazonaws.com/desk/malm-desk-white.webp'],
    category: 'Desk',
    brand: 'Ikea',
    colors: ['white'],
    material: 'Wood',
    heightAdjustable: false,
  },
  {
    name: 'Ikea HAUGA desk',
    price: 6990,
    originalPrice: 8455,
    description: '',
    images: ['https://wfh-store.s3.amazonaws.com/desk/hauga-desk-beige.webp'],
    category: 'Desk',
    brand: 'Ikea',
    colors: ['brown'],
    material: 'Wood',
    heightAdjustable: false,
  },
];

const HEADPHONES: Omit<ProductHeadphoneRequest, 'kind'>[] = [
  {
    type: 'Wired',
    connectivity: '3.5mm Jack',
    name: 'Razer Kraken V3 X Over Ear Wired Gaming Headset',
    price: 6950,
    originalPrice: 9999,
    description:
      'Immerse into the amazing audio performance of the Razer Kraken V3X Over-Ear Wired Gaming Headphone with Mic.',
    images: [
      'https://cdn.shopify.com/s/files/1/0153/8863/products/Headphone-Zone-Razer-Kraken-V3-X-Gaming-Headset-gallery-1_800x.jpg?v=1618918980',
    ],
    category: 'Headphone',
    brand: 'Razer',
    colors: ['black'],
  },
  {
    type: 'Wireless',
    connectivity: 'Bluetooth 5.0',
    name: 'Sony WH-1000XM3 Bluetooth Wireless Over Ear Headphones',
    price: 16990,
    originalPrice: 29990,
    description:
      'WH-1000XM3 impressed us with its sound quality, comfort, sleek, lightweight design, stellar battery life and rock solid connectivity.',
    images: ['https://m.media-amazon.com/images/I/6125kwHG4gL._SL1500_.jpg'],
    category: 'Headphone',
    brand: 'Sony',
    colors: ['black'],
  },
  {
    type: 'Wireless',
    connectivity: '3.5mm Jack',
    name: 'Sony WH-1000XM4 Headphones',
    price: 26990,
    originalPrice: 29990,
    description:
      'Industry Leading Wireless Noise Cancelling Bluetooth Headphones with Mic for Phone Calls, 30 Hours Battery Life, Quick Charge, Touch Control and Alexa Voice Control.',
    images: [''],
    category: 'Headphone',
    brand: 'Sony',
    colors: ['black'],
  },
  {
    type: 'Wireless',
    connectivity: '3.5mm Jack',
    name: 'Razer Barracuda X',
    price: 11499,
    originalPrice: 12499,
    description: '',
    images: [''],
    category: 'Headphone',
    brand: 'Razer',
    colors: ['black'],
  },
  {
    type: 'Wired',
    connectivity: '3.5mm Jack',
    name: 'Razer BlackShark V2 X',
    price: 7599,
    originalPrice: 7999,
    description: '',
    images: [''],
    category: 'Headphone',
    brand: 'Razer',
    colors: ['black'],
  },
];

const MONITORS: Omit<ProductMonitorRequest, 'kind'>[] = [
  {
    type: '4K IPS',
    size: '27 Inch',
    inputs: '2x HDMI, 1x VGA, 1x DisplayPort',
    resolution: '3840 x 2160',
    name: 'Acer Predator 27-inch 4K UHD IPS 1MS 144 Hz Gaming Monitor',
    price: 55999,
    originalPrice: 72200,
    description:
      'The Predator XB273K Ultra HD display with 4K resolution is all about no compromises on gaming performance, color or speed. This 27-inch (3840 x 2160) monitor combines jaw dropping specs including an IPS panel that supports blazing-fast 144Hz refresh rate. ',
    images: ['https://m.media-amazon.com/images/I/81yZnpFoxwL._SL1500_.jpg'],
    category: 'Monitor',
    brand: 'Acer',
    colors: ['black'],
  },
  {
    type: 'UHD IPS',
    size: '28 Inch',
    inputs: '2x HDMI, 1x Thunderbolt, 1x DisplayPort',
    resolution: '3840 x 2160',
    name: 'Acer Predator X28 28 Inch UHD (3840 X 2160) 0.2 ms 152Hz (Overclock) NVIDIA G-SYNC Gaming Monitor',
    price: 74999,
    originalPrice: 100000,
    description:
      'Push your gameplay to extremes with the 152Hz refresh rate in 4K UHD and put your eSports skills to the test with NVIDIA Reflex Latency Analyzer. ',
    images: ['https://m.media-amazon.com/images/I/613a-3jtieL._SL1500_.jpg'],
    category: 'Monitor',
    brand: 'Acer',
    colors: ['black'],
  },
  {
    type: 'Curved LED',
    size: '23.5 Inch',
    resolution: '1920 x 1080',
    inputs: '2x HDMI, 1x VGA, 1x DisplayPort',
    name: 'Samsung 23.5 inch Curved LED Backlit Computer Monitor',
    price: 12399,
    originalPrice: 14798,
    description: ' ',
    images: ['https://m.media-amazon.com/images/I/71nplbAMwzL._SL1202_.jpg'],
    category: 'Monitor',
    brand: 'Samsung',
    colors: ['black'],
  },
  {
    type: 'Curved LED',
    size: '23.5 Inch',
    resolution: '1920 x 1080',
    inputs: '2x HDMI, 1x VGA, 1x DisplayPort',
    name: 'Samsung 23.5 inch Curved LED Backlit Computer Monitor',
    price: 12399,
    originalPrice: 14798,
    description: ' ',
    images: ['https://m.media-amazon.com/images/I/71nplbAMwzL._SL1202_.jpg'],
    category: 'Monitor',
    brand: 'Samsung',
    colors: ['black'],
  },
  {
    type: 'FHD LED',
    size: '27 Inch',
    resolution: '1920 x 1080',
    inputs: '2x HDMI, 1x VGA, 1x DisplayPort',
    name: 'Dell Professional 27 inch Full HD Monitor',
    price: 20898,
    originalPrice: 39900,
    description: ' ',
    images: ['https://m.media-amazon.com/images/I/61v+Nizxe3L._SL1280_.jpg'],
    category: 'Monitor',
    brand: 'Dell',
    colors: ['grey'],
  },
  {
    type: 'Curved LED',
    size: '31.5 Inch',
    resolution: '1920 x 1080',
    inputs: '2x HDMI, 1x VGA, 1x DisplayPort',
    name: 'Acer Nitro XZ320QX 31.5 Inch 1500R Curved Full HD LED Gaming Monitor ',
    price: 27999,
    originalPrice: 38100,
    description:
      'Speed is at the core of this curved Zero Frame Monitor with refresh rate revving up to 240Hz, 1 MS VRB response Time and Full HD Resolution.',
    images: ['https://m.media-amazon.com/images/I/81Gf+JF4AGS._SL1500_.jpg'],
    category: 'Monitor',
    brand: 'Acer',
    colors: ['black'],
  },
  {
    type: 'IPS',
    size: '24 Inch',
    resolution: '1920 x 1080',
    inputs: '2x HDMI, 1x VGA, 1x DisplayPort',
    name: 'Samsung 24 inch IPS, 3 Side Bezel Less Flat LED Monitor',
    price: 14499,
    originalPrice: 15498,
    description: ' ',
    images: ['https://m.media-amazon.com/images/I/91TS0uHjMbL._SL1500_.jpg'],
    category: 'Monitor',
    brand: 'Samsung',
    colors: ['grey'],
  },
];

export type Items =
  | Omit<ProductMonitorRequest, 'kind'>
  | Omit<ProductHeadphoneRequest, 'kind'>
  | Omit<ProductKeyboardRequest, 'kind'>
  | Omit<ProductMouseRequest, 'kind'>
  | Omit<ProductDeskRequest, 'kind'>
  | Omit<ProductChairRequest, 'kind'>;

export const PRODUCTS: { items: Items[]; kind: string }[] = [
  { items: KEYBOARDS, kind: 'ProductKeyboard' },
  { items: MONITORS, kind: 'ProductMonitor' },
  { items: HEADPHONES, kind: 'ProductHeadphone' },
  { items: MOUSE, kind: 'ProductMouse' },
  { items: CHAIR, kind: 'ProductChair' },
  { items: DESK, kind: 'ProductDesk' },
];
